"""
SÜSSE WURST ADDRESS GENERATOR LISTS
AUTHOR: N.F. DESMOND
DATE: JULY 2025
DESCRIPTION: This module contains lists of adjectives, nouns, names, directional indicators,
address paths, and store locations used by the Süsse Wurst address generator program.
"""

ADJECTIVE = [
    'Dry',
    'Stoney',
    'Cloudy',
    'Lilac',
    'Smooth',
    'Small',
    'High',
    'Ultimate',
    'Clear',
    'Galloping',
    'Full',
    'Under',
    'Merry',
    'Straight',
    'Falling',      
    'Drowning',
    'Old',
    'Crooked',
    'Shadowy',
    'Quiet',
    'Bright',
    'Shooting',
    'Little',
    'Sideways',
    'Silent',
    'Windy',
    'Long',
    'Short',
    'Narrow',
    'Alabaster',
    'White',
    'Dark',
    'Blue',
    'Solar',
    'Handsome',
    'Dusty',
    'Bent',
    'Idle',
    'Silver',
    'Winding',
    'Tender',
    'Red',
    'Silky',
    'Soft',
    'Rough',    
    'Sleepy',
    'Low',
    'Sweet',
    'Sloping',
    'Sliding',
    'Falling',
    'Slow',
    'Running',
    'Hanging',
    'Folding',
    'Rugged',
    'Waving',
    'Weathered',
    'Folded',
    'Velvet',
    'Dancing',
    'Faded',
    'Stitched',
    'Patchy',
    'Sunken',
    'Hidden',
    'Smokey',
    'Quick',
    'Humble',
    'Woven',
    'Shaved',
    'Broken',
    'Lonely',
    'Grey',
    'Turning',
    'Callous',
    'Loose',
    'Sandy',
    'Burnt',
    'Pointed',
    'Gold',
    'Copper',
    'Sharp',
    'Salty',
    'Hollow',
    'Mellow',
    'Clever',
    'Cracked',
    'Stacked',
    'Twisted',
    'Piney',
    'Etched',
    'Hazy',
    'Full',
    'Strong',
    'Grassy',
    'Galloping',
    'Lost',
    'Lean',
    'Slender',
    'Orange',
    'Leaning',
    'Secret',
    'Ghostly',
    'Fallen',
    'Wrong',
    'Round',
    'Sheer',
    'Wet',
    'Sapphire',
    'Tarry',
    'Lit',
    'Light',
    'Soaring',
    'Rusty',
    'Petrified',
    'Flooded',
    'Torn',
    'Cotton',
    'Painted',
    'Dusted',          
    'Chipped',
    'Lashed',
    'Deep',
    'Thick',
    'Shiny',
    'Creeping',
    'Full',
    'Fiery',
    'Hot',
    'Pierced',
    'Rocky',    
    'Talking',
    'Wheeling',
    'Biting',
    'Ruined',
    'Striped',
    'Sacred',
    'Brittle',
    'Golden',
    'Rapid',
    'Slipping',
    'Double',
    'Shady',
    'Majestic',
    'Rippling',
    'Riding',
    'Stiff',
    'Iron',
    'Flat',
    'Bushy',
    'Resting',
    'Darling',
    'Halting',
    'Sour',
    'Branded',
    'Pale',
    'Shrinking',
    'Sinking',
    'Mild',
    'Peaceful',
    'Tired',
    'Swinging',
    'Leaping',
    'Shabby',
    'Happy',
    'Bending',
    'Pretty',
    'Rising',
    'Laughing',
    'Jilted'
]

NOUN = [
    'Hope',
    'Bee',
    'Apple',
    'Bento',
    'Mule',
    'Summer',   
    'River',
    'Sandhill',
    'Bluejay',
    'Hare',
    'Weston',
    'Sunset',
    'Glass',
    'Sultan',
    'Goldstar',
    'Bakers',
    'Song',
    'Cedar',
    'Melon',
    'Hill',
    'Bend',
    'Juncture',
    'Cord',
    'Wagon',
    'Horse',
    'Bobcat',
    'Jump',
    'Mosquito',
    'Skipper',
    'Rope',
    'Garden',
    'Field',
    'Grove',    
    'Fin',
    'Fair',
    'Hoof',
    'Basin',
    'Riverbed',
    'Hide',
    'Finch',
    'Catch',
    'Wood',
    'Cacti',
    'Eagle',
    'Weed',
    'Surprise',
    'Echo',
    'Path',
    'Drift',   
    'Monk',
    'Steppe',
    'Butte',
    'Antler',
    'Town',
    'Prairie',
    'Feather',
    'Leg',
    'Mill',
    'Mine',
    'Hammer',
    'Courthouse',
    'Ranch',
    'Yard',
    'Coach',    
    'Quest',
    'Waterway',
    'Gate',
    'Flower',
    'Rose',
    'Fire',
    'Fletchers',
    'Pueblo',
    'Hut',
    'Heart',
    'Boot',
    'Cart',
    'Cloak',
    'Dam',
    'Water',
    'Lake',
    'Morning',
    'Raven',
    'Dragon',
    'Hand',
    'Fence',
    'Ribbon',
    'Arrow',
    'Venture',
    'Lemon',
    'Reed',
    'Rock',
    'Stone',
    'Needle',
    'Cyst',
    'Scorpion',
    'Spider',
    'Palo Verde',
    'Park',
    'Cabin',
    'Valley',
    'Hole',
    'Cactus',
    'Wall',
    'Bottle',
    'Saloon',
    'Pit',
    'Root',
    'Harpstring',
    'Dagger',
    'House',
    'Camel',
    'Barn',
    'Stick',
    'Corral',
    'Tombstone',
    'Heather',
    'Nectar',
    'Canyon',
    'Monument',
    'Resort',
    'Reservation',
    'Scout',
    'Warrior',
    'Trail',
    'Gun',
    'Mesa',
    'Plateau',
    'Camp',
    'Peak',
    'Crater',
    'Desert',
    'Mission',
    'Church',
    'Bowl',
    'Cricket',
    'Fort',
    'Stone',
    'Cypress',
    'Coyote',
    'Hedge',
    'Burrow',
    'Trout',
    'Nest',
    'Plain',
    'Bridge',
    'Settlement',
    'Courtyard',
    'Puddle',
    'Head',
    'Hat',
    'Harness',
    'Wren',
    'Ravine',
    'Vine',
    'Tumbleweed',
    'Cap',
    'Barrell',
    'Dirt',
    'Horn',
    'Cavern',
    'Bird',
    'Phantom',
    'Ditch',
    'Drain',
    'Gully',
    'Thorn',
    'Cattle',
    'Chestnut',
    'Bottom',
    'Deer',
    'Lynx',
    'Quilt',
    'Bean',
    'Lover'
]

NAME = [
    'Tootheye',
    'Tigerlily',
    'Sycamore',
    'Saddlepush',
    'Emerson',
    'Tidal Wave',
    'Elbow Weave',
    'Mosshill',
    'Needlepoint',
    'Moses Jones',
    'Black Sesame',
    'Andrews',
    'Atlantic',
    'Clear Day',
    'Worthwhile',
    'Bearskin',
    'Ancestral',
    'Wicketts',
    'Deerhead',
    'Highcrest',
    'Beer Grove',
    'Mountain View',
    'Winnow Hop',
    'Long View',
    'Bricketts',
    'Skylight Park',
    'Red Dust',
    'Small Bowl',
    'Green Peaks',
    'Sommersville',
    'Castodia',
    'Meyers',
    'Freeman',
    'Idaho Port',
    'Kennedy',
    'Drunk Owl',
    'Blue Tortoise',
    'Low Rise',
    'Pennderby',
    'Stewartson',
    'Parading Cloud',
    'Bearded Fence',
    'Tree Root',
    'Bloomlace',
    'Turnover',
    'Pilgrim',
    'Longbow',
    'Marigold',
    'Tallman',
    'Old Slingshot',
    'New Town',
    'Riverside',
    'Good Sister',
    'Welchman',
    'Wormwood',
    'Torrance',
    'Smiling Fish',
    'Citrus',
    'Scratched Bark',
    'Violet Stone',
    'Sexton',
    'Lazy Foxhen',
    'Templeton',
    'Slender Blossom',
    'Top Knob',
    'Tied Lasso',
    'Wicked Wart',
    'Rainwell',
    'Sudden Fall',
    'Egg Stealer',
    'Black Pitch',
    'Emerald',
    'Youngblood',
    'Shipyard',
    'Resting',
    'Highmind',
    'Braintree',
    'Cornerbend',
    'Custard',
    'Camp Bellow',
    'Braggsworth',
    'Thieves Den',
    'Trusted Oak',
    'Winebarrel',
    'Blainesway',
    'Quarterby',
    'Inkwell',
    'Driftwood',
    'Broken Wheel',
    'Tinted Window',
    'Slowfalls',
    'Jackrabbit',
    'Pycket',
    'Sunder',
    'Fencers Lot',
    'Kingturn',
    'Footfall',
    'Applecore',
    'Fixed',
    'Pollen',
    'Hardtack',
    'Seabiscuit',
    'Cracked Seed',
    'Andromeda',
    'Kirkly',
    'Olive Tree',
    'Seqouia',
    'Coffee Bean',
    'Ambrosia',
    'Diamond',
    'Ancestral',
    'Noble Sir',
    'Gingerstem',
    'Goldwater',
    'Coronado',
    'Blue Thunderbird',
    'Flowing Gold',
    'Leafy Tunnel',
    'Curly Horse',
    'Sunstick',
    'Good Pickle',
    'Eddlewood',
    'Porters',
    'Striped Cat',
    'Hornet Sting',
    'Happy Trails',
    'Bitter Gum',
    'Pink Petal',
    'Ripped Pouch',
    'Twilight Hedge',
    'Stacked Brick',
    'Yellowjacket',
    'Nested Crow',
    'Waterspill',
    'Bankmore',
    'Veronica',
    'Dayton',
    'Cowtongue',
    'Pebblestep',
    'Butterbean',
    'Victoria',
    'Cow Skull',
    'Violet Stem',
    'Humming Bird',
    'Coal Mine',
    'Jesters Joke',
    'Carolina',
    'Seabender',
    'Staffmoore',
    'Teetering Brook',
    'Good Eye',
    'Orange Petal',
    'Low Sights',
    'Riddleride',
    'Roundabout',
    'Crying Moon',
    'Amber Bed',
    'Mosquito Nest',
    'Golden Arrow',
    'Derry',
    'Quick Hunt',
    'Summerville',
    'Lazy Cloud',
    'Petal Fall',
    'Fading Bark',
    'Teal Settlement',
    'Soaring Heights',
    'Grand Testament',
    'Silver Slice',
    'Wilting Stem',
    'Middlebick',
    'Lost Dog'
]

STREET_NAME = [NAME, NOUN, 'numbered']

DIRECTIONAL = ['E', 'N', 'S', 'W',
               'NE', 'SE', 'NW', 'SW']

ADDRESS_PATH = ['Avenue', 'Boulevard', 'Drive', 'Circle', 'Court',
                'Lane', 'Place','Road', 'Street', 'Way']

PV_SCOTTS_STORE = ['Paradise Valley', 'Phoenix', 'Scottsdale']

PHX_STORE = ['Tolleson', 'Glendale', 'Phoenix', 'Tempe']

TEMPE_STORE = ['Mesa', 'Phoenix', 'Tempe']

MESA_STORE = ['Gilbert', 'Mesa', 'Tempe']

CHANDLER_STORE = ['Mesa','Gilbert', 'Chandler', 'Sun Lakes']

GLEN_STORE = ['Glendale', 'Peoria', 'Phoenix']

HEND_STORE = ['Henderson', 'Las Vegas']
